name: CrystalGuard
author: Glamify
version: '${project.version}'
main: games.sparking.crystalguard.CrystalGuard
commands:
  spectator:
    aliases: [ spectate, spec ]
  staffmode:
    aliases: [ sm, modmode, mm ]
  vanish:
    aliases: [ v, van, minivan ]
  punish:
    aliases: [ p ]
  report:
    aliases: [ hackerreport, hackereport, hr, crystalguardreport, crystalguard, cgr, cg, chatreport, cr ]
  chatreportview:
    aliases: [ viewchatreport, crv ]
  reporthandle:
    aliases: [ rh ]
  reportclose:
    aliases: [ rc ]
  dev:
    aliases: [ gm, hub, lobby ]