name: CrystalSpec
author: Glamify
version: '${project.version}'
main: games.sparking.crystalguard.CrystalGuard
commands:
  spectator:
    aliases: spec
  staffmode:
    aliases: [ sm, modmode, mm ]
  vanish:
    aliases: [ v, van, minivan ]
  punish:
    aliases: [ p ]
  report:
    aliases: [ cr, chatreport ]
  chatreportview:
    aliases: [ crv ]
  reporthandle:
    aliases: [ rh ]
  reportdebug:
    aliases: [ rd ]